#!/usr/bin/bash

# Attemp to Terminate and Remove previous session
if [ -f ubotindo.session ]; then
    kill $(pgrep -f 'python3 -m ubotindo')
    rm -f ubotindo.session-journal ubotindo.session
fi

# start
python3 -m ubotindo